routes/web.php
<?php

Route::get('/', function(){ return view('auth.login'); });

Route::get('/user-profile', function () {
    return view('dashboard/yourprofile');
});

Route::resource('reg', 'Auth\MyRegisterController');
Auth::routes();

Route::group(['middleware'=>['auth','verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // ===== Member =====
    Route::resource('member', 'Dashboard\Member\MemberController');
    Route::resource('profile', 'Dashboard\Member\ProfileController');
    
    Route::get('api.member','Dashboard\Member\MemberController@memberApi')->name('api.member');

    Route::get('password/{uuid}/edit','Dashboard\Member\ProfileController@passwordEdit')->name('password.edit');
    Route::patch('password/{uuid}','Dashboard\Member\ProfileController@passwordUpdate')->name('password.update');


});

app/Http/Controllers/Dashboard/Member/MemberController.php
<?php

namespace App\Http\Controllers\Dashboard\Member;

use Ramsey\Uuid\Uuid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\DB;
use App\Models\RoleUser;
use App\Models\Member;
use App\Models\Province;
use App\Models\City;
use Illuminate\Support\Facades\Auth;

class MemberController extends Controller
{
    public function index()
    {
        return view('dashboard.member.all_member');
    }
    
    public function create()
    {
        $province = Province::get();
        $city = DB::table('provinces')->leftJoin('cities','provinces.id','=','cities.province_id')->get();

        return view('dashboard.member.add_member',compact('province','city'));
    }
    
    public function store(Request $request)
    {
        $user2 = User::where('id',Auth::user()->id)->first();
        $member = $user2->member()->first();

        $province = Province::where('id',$member->province)->first();
        $city = City::where('id',$member->city)->first();

        if (Auth::user()->hasRole('master')) 
        {
            $p = $request->province;
            $c = $request->city;
            
        }
        else
        {
            $p = $province->id;
            $c = $city->id;
        }

        $user = new User;

        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required|unique:users',
            'password' => 'required|min:8'
        ]);
        
        $user->uuid = Uuid::uuid4();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->email_verified_at = now();
        $user->password = bcrypt($request->password);
        $user->save();
        
        //Kode Jabatan 
        if ($request->position == 'admin') 
        {
            $jbt = 1;
        }
        elseif ($request->position == 'member') 
        {
            $jbt = 2;
        }

        $memberid = $jbt.date('ym').$user->id;

        Member::create(
            [
                'user_id'=>$user->id,
                'memberid' => $memberid,
                'address' => $request->address,
                'province' => $p,
                'city' => $c,
                'hp' => $request->hp,
                'birth_date' => date('Y-m-d',strtotime($request->birth_date)),
                'birth_place' => $request->birth_place,
                'gender' => $request->gender,
                'education' => $request->education,
                'status' => $request->status,
                'job' => $request->job,
                'skill' => $request->skill,
                'fb' => $request->fb,
                'position' => $request->position
            ]
        );

        $member = Member::where('user_id','=',$user->id)->first();

        if ($request->hasFile('photo')) 
        {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/member',$photoName);
            $member->photo = $photoName;
        }

        $member->update();

        if ($request->position == 'admin') 
        {
            RoleUser::create(['user_id' => $user->id,'role_id' => 2]);
            RoleUser::create(['user_id' => $user->id,'role_id' => 3]);
        }
        elseif ($request->position == 'member') 
        {
            RoleUser::create(['user_id' => $user->id,'role_id' => 3]);
        }

        return redirect()->route('home')->with('success','Berhasil Menambahkan'); 
    }

    
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();
        $province = Province::where('id',$member->province)->first();
        $city = City::where('id',$member->city)->first();

        return view('dashboard.member.detail_member',compact('user','member','province','city'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();
        $province = Province::get();
        $city = DB::table('provinces')->leftJoin('cities','provinces.id','=','cities.province_id')->get();
        $province2 = Province::where('id',$member->province)->first();
        $city2 = City::where('id',$member->city)->first();

        return view('dashboard.member.edit_member',compact('user','member','province','city','province2','city2'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required',
            'password' => 'required|min:8'
        ]);

        $user2 = User::where('id',Auth::user()->id)->first();
        $member = $user2->member()->first();

        $province = Province::where('id',$member->province)->first();
        $city = City::where('id',$member->city)->first();

        if (Auth::user()->hasRole('master')) 
        {
            $p = $request->province;
            $c = $request->city;
            
        }
        else
        {
            $p = $province->id;
            $c = $city->id;
        }
        
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;

        if ($request->password != $user->password) 
        {
            $user->password = bcrypt($request->password);
        }
        $user->update();

        //=========== member =============
        $member->province = $p;
        $member->city = $c;
        $member->address = $request->address;
        $member->hp = $request->hp;
        $member->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $member->birth_place = $request->birth_place;
        $member->gender = $request->gender;
        $member->education = $request->education;
        $member->status = $request->status;
        $member->job = $request->job;
        $member->skill = $request->skill;
        $member->fb = $request->fb;

        if ($request->hasFile('photo')) 
        {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/member',$photoName);
            $member->photo = $photoName;
        }
        $member->update();

        return redirect()->back()->with('success','Edit Success');
    }
    
    public function destroy($id)
    {
        $member = Member::find($id);
        $user = User::where('id',$member->user_id)->first();
        // dd($user);

        $user->delete();
    }

    public function memberApi(){
        $member = DB::table('users')->rightJoin('members','members.user_id','=','users.id');

        return $this->displayMember($member);
    }
}

app/Http/Controllers/Dashboard/Member/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Models\Member;

class ProfileController extends Controller
{
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = Member::where('user_id',$user->id)->first();

        // dd($user);

        return view('dashboard.member.user.profile.detail_profile',compact('user','member'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();

        return view('dashboard.member.user.profile.edit_profile',compact('user','member'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required'
        ]);
        
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;
        
        $user->update();

        //=========== member =============
        $member->province = $request->province;
        $member->address = $request->address;
        $member->hp = $request->hp;
        $member->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $member->birth_place = $request->birth_place;
        $member->gender = $request->gender;

        if ($request->hasFile('photo')) 
        {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/member',$photoName);
            $member->photo = $photoName;
        }
        $member->update();

        return redirect()->back()->with('success','Edit Success');
    }

    public function passwordEdit($uuid)
    {
        $user = User::where('uuid',$uuid)->first();

        return view('dashboard.member.user.profile.edit_password',compact('user'));
    }

    public function passwordUpdate(Request $request, $id)
    {
        $user = User::where('uuid',$id)->first();
        
        if ($request->password == $request->password2 && strlen($request->password) >= 8) {
            $user->password = bcrypt($request->password);
            $user->update();

            return redirect()->back()->with('success','Berhasil Merubah Password');
        }else{
            return redirect()->back()->with('info','Password tidak sama atau kurang dari 8 karakter');
        }
        
    }
}

resources/views/dashboard/master.blade.php
<!--

=========================================================
* Argon Dashboard - v1.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  @yield('title')
  <!-- Favicon -->
  <link href="{{ url('img/brand/favicon.png') }}" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="{{ url('js/plugins/nucleo/css/nucleo.css') }}" rel="stylesheet" />
  <link href="{{ url('js/plugins/@fortawesome/fontawesome-free/css/all.min.css') }}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{{ url('css/argon-dashboard.css?v=1.1.0') }}" rel="stylesheet" />
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {{-- Data Table --}}
  <link href="{{ url('datatable/style.css') }}" rel="stylesheet" />
</head>

<body class="">
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0" href="./">
        {{-- <img src="{{ url('img/brand/blue.png') }}" class="navbar-brand-img" alt="..."> --}}
      </a>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
        <li class="nav-item dropdown">
          <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{{ url('img/theme/team-4-800x800.jpg') }}">
              </span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <div class=" dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-settings-gear-65"></i>
              <span>Settings</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-calendar-grid-58"></i>
              <span>Activity</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
          </div>
        </li>
      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="./index.html">
                <img src="{{ url('img/brand/blue.png') }}">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Form -->
        <form class="mt-4 mb-3 d-md-none">
          <div class="input-group input-group-rounded input-group-merge">
            <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <span class="fa fa-search"></span>
              </div>
            </div>
          </div>
        </form>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading text-muted">Users</h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          @if (Auth::user()->hasRole('admin'))
          <li class="nav-item">
            <a class="nav-link" href="{{route('member.index')}}">
              <i class="fas fa-users text-primary"></i> All Users
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('member.create')}}">
              <i class="fas fa-user-plus text-primary"></i> Add New
            </a>
          </li>
          @endif
          <li class="nav-item">
            <a class="nav-link" href="./user-profile">
              <i class="fas fa-address-card text-primary"></i> Your Profile
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  @yield('content')

  <!--   Core   -->
  <script src="{{ url('js/plugins/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url('js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
  <!--   Optional JS   -->
  <script src="{{ url('js/plugins/chart.js/dist/Chart.min.js') }}"></script>
  <script src="{{ url('js/plugins/chart.js/dist/Chart.extension.js') }}"></script>
  <!--   Argon JS   -->
  <script src="{{ url('js/argon-dashboard.min.js?v=1.1.0') }}"></script>
  {{-- <script src="https://cdn.trackjs.com/agent/v3/latest/t.js') }}"></script>
  <script>
    window.TrackJS &&
      TrackJS.install({
        token: "ee6fab19c5a04ac1a32a645abde4613a",
        application: "argon-dashboard-free"
      });
  </script> --}}
  <script src="{{ asset('datatable/js.js') }}"></script>
  @yield('js')
  <script src="{{ asset('js/dashboard.js') }}"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
 <script>
 $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
  
</body>

</html>

resources/views/dashboard/yourprofile.blade.php
@extends('dashboard.master')

@section('content')
<div class="main-content">
    @include('dashboard.components.menu_dropdown')
  <!-- Header -->
  <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 600px; background-image: url(../img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <!-- Header container -->
    <div class="container-fluid d-flex align-items-center">
      <div class="row">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">Hello Jesse</h1>
          <p class="text-white mt-0 mb-5">This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks</p>
          <a href="#!" class="btn btn-info">Edit profile</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image">
                <a href="#">
                  <img src="{{ url('img/theme/team-4-800x800.jpg') }}" class="rounded-circle">
                </a>
              </div>
            </div>
          </div>
          <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
            <div class="d-flex justify-content-between">
              <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
              <a href="#" class="btn btn-sm btn-default float-right">Message</a>
            </div>
          </div>
          <div class="card-body pt-0 pt-md-4">
            <div class="row">
              <div class="col">
                <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                  <div>
                    <span class="heading">22</span>
                    <span class="description">Friends</span>
                  </div>
                  <div>
                    <span class="heading">10</span>
                    <span class="description">Photos</span>
                  </div>
                  <div>
                    <span class="heading">89</span>
                    <span class="description">Comments</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center">
              <h3>
                Jessica Jones<span class="font-weight-light">, 27</span>
              </h3>
              <div class="h5 font-weight-300">
                <i class="ni location_pin mr-2"></i>Bucharest, Romania
              </div>
              <div class="h5 mt-4">
                <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
              </div>
              <div>
                <i class="ni education_hat mr-2"></i>University of Computer Science
              </div>
              <hr class="my-4" />
              <p>Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music.</p>
              <a href="#">Show more</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow">
          <div class="card-header bg-white border-0">
            <div class="row align-items-center">
              <div class="col-8">
                <h3 class="mb-0">My account</h3>
              </div>
              <div class="col-4 text-right">
                <a href="#!" class="btn btn-sm btn-primary">Settings</a>
              </div>
            </div>
          </div>
          <div class="card-body">
            <form>
              <h6 class="heading-small text-muted mb-4">User information</h6>
              <div class="pl-lg-4">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="form-control-label" for="input-username">Username</label>
                      <input type="text" id="input-username" class="form-control form-control-alternative" placeholder="Username" value="lucky.jesse">
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="form-control-label" for="input-email">Email address</label>
                      <input type="email" id="input-email" class="form-control form-control-alternative" placeholder="jesse@example.com">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="form-control-label" for="input-first-name">First name</label>
                      <input type="text" id="input-first-name" class="form-control form-control-alternative" placeholder="First name" value="Lucky">
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="form-control-label" for="input-last-name">Last name</label>
                      <input type="text" id="input-last-name" class="form-control form-control-alternative" placeholder="Last name" value="Jesse">
                    </div>
                  </div>
                </div>
              </div>
              <hr class="my-4" />
              <!-- Address -->
              <h6 class="heading-small text-muted mb-4">Contact information</h6>
              <div class="pl-lg-4">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label class="form-control-label" for="input-address">Address</label>
                      <input id="input-address" class="form-control form-control-alternative" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09" type="text">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label class="form-control-label" for="input-city">City</label>
                      <input type="text" id="input-city" class="form-control form-control-alternative" placeholder="City" value="New York">
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label class="form-control-label" for="input-country">Country</label>
                      <input type="text" id="input-country" class="form-control form-control-alternative" placeholder="Country" value="United States">
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label class="form-control-label" for="input-country">Postal code</label>
                      <input type="number" id="input-postal-code" class="form-control form-control-alternative" placeholder="Postal code">
                    </div>
                  </div>
                </div>
              </div>
              <hr class="my-4" />
              <!-- Description -->
              <h6 class="heading-small text-muted mb-4">About me</h6>
              <div class="pl-lg-4">
                <div class="form-group">
                  <label>About Me</label>
                  <textarea rows="4" class="form-control form-control-alternative" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer -->
    <footer class="footer">
      <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
          <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
          </div>
        </div>
        <div class="col-xl-6">
          <ul class="nav nav-footer justify-content-center justify-content-xl-end">
            <li class="nav-item">
              <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
            </li>
            <li class="nav-item">
              <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </div>
</div>
@endsection