routes/web.php
<?php

Route::get('/', function(){ return view('auth.login'); });

Route::get('/user-profile', function () {
    return view('dashboard/yourprofile');
});

Route::resource('reg', 'Auth\MyRegisterController');
Auth::routes();

Route::group(['middleware'=>['auth','verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // ===== Member =====
    Route::resource('member', 'Dashboard\Member\MemberController');
    Route::resource('profile', 'Dashboard\Member\ProfileController');
    
    Route::get('api.member','Dashboard\Member\MemberController@memberApi')->name('api.member');

    Route::get('password/{uuid}/edit','Dashboard\Member\ProfileController@passwordEdit')->name('password.edit');
    Route::patch('password/{uuid}','Dashboard\Member\ProfileController@passwordUpdate')->name('password.update');


});

app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $guarded = ['id'];
    protected $table = 'members';

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Dashboard/Member/MemberController.php
<?php

namespace App\Http\Controllers\Dashboard\Member;

use Ramsey\Uuid\Uuid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\DB;
use App\Models\RoleUser;
use App\Models\Member;
use App\Models\Province;
use App\Models\City;
use Illuminate\Support\Facades\Auth;

class MemberController extends Controller
{
    public function index()
    {
        return view('dashboard.member.all_member');
    }
    
    public function create()
    {
        $province = Province::get();
        $city = DB::table('provinces')->leftJoin('cities','provinces.id','=','cities.province_id')->get();

        return view('dashboard.member.add_member',compact('province','city'));
    }
    
    public function store(Request $request)
    {
        $user2 = User::where('id',Auth::user()->id)->first();
        $member = $user2->member()->first();

        $province = Province::where('id',$member->province)->first();
        $city = City::where('id',$member->city)->first();

        if (Auth::user()->hasRole('master')) 
        {
            $p = $request->province;
            $c = $request->city;
            
        }
        else
        {
            $p = $province->id;
            $c = $city->id;
        }

        $user = new User;

        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required|unique:users',
            'password' => 'required|min:8'
        ]);
        
        $user->uuid = Uuid::uuid4();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->email_verified_at = now();
        $user->password = bcrypt($request->password);
        $user->save();
        
        //Kode Jabatan 
        if ($request->position == 'admin') 
        {
            $jbt = 1;
        }
        elseif ($request->position == 'member') 
        {
            $jbt = 2;
        }

        $memberid = $jbt.date('ym').$user->id;

        Member::create(
            [
                'user_id'=>$user->id,
                'memberid' => $memberid,
                'address' => $request->address,
                'province' => $p,
                'city' => $c,
                'hp' => $request->hp,
                'birth_date' => date('Y-m-d',strtotime($request->birth_date)),
                'birth_place' => $request->birth_place,
                'gender' => $request->gender,
                'education' => $request->education,
                'status' => $request->status,
                'job' => $request->job,
                'skill' => $request->skill,
                'fb' => $request->fb,
                'position' => $request->position
            ]
        );

        $member = Member::where('user_id','=',$user->id)->first();

        if ($request->hasFile('photo')) 
        {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/member',$photoName);
            $member->photo = $photoName;
        }

        $member->update();

        if ($request->position == 'admin') 
        {
            RoleUser::create(['user_id' => $user->id,'role_id' => 2]);
            RoleUser::create(['user_id' => $user->id,'role_id' => 3]);
        }
        elseif ($request->position == 'member') 
        {
            RoleUser::create(['user_id' => $user->id,'role_id' => 3]);
        }

        return redirect()->route('home')->with('success','Berhasil Menambahkan'); 
    }

    
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();
        $province = Province::where('id',$member->province)->first();
        $city = City::where('id',$member->city)->first();

        return view('dashboard.member.detail_member',compact('user','member','province','city'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();
        $province = Province::get();
        $city = DB::table('provinces')->leftJoin('cities','provinces.id','=','cities.province_id')->get();
        $province2 = Province::where('id',$member->province)->first();
        $city2 = City::where('id',$member->city)->first();

        return view('dashboard.member.edit_member',compact('user','member','province','city','province2','city2'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required',
            'password' => 'required|min:8'
        ]);

        $user2 = User::where('id',Auth::user()->id)->first();
        $member = $user2->member()->first();

        $province = Province::where('id',$member->province)->first();
        $city = City::where('id',$member->city)->first();

        if (Auth::user()->hasRole('master')) 
        {
            $p = $request->province;
            $c = $request->city;
            
        }
        else
        {
            $p = $province->id;
            $c = $city->id;
        }
        
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;

        if ($request->password != $user->password) 
        {
            $user->password = bcrypt($request->password);
        }
        $user->update();

        //=========== member =============
        $member->province = $p;
        $member->city = $c;
        $member->address = $request->address;
        $member->hp = $request->hp;
        $member->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $member->birth_place = $request->birth_place;
        $member->gender = $request->gender;
        $member->education = $request->education;
        $member->status = $request->status;
        $member->job = $request->job;
        $member->skill = $request->skill;
        $member->fb = $request->fb;

        if ($request->hasFile('photo')) 
        {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/member',$photoName);
            $member->photo = $photoName;
        }
        $member->update();

        return redirect()->back()->with('success','Edit Success');
    }
    
    public function destroy($id)
    {
        $member = Member::find($id);
        $user = User::where('id',$member->user_id)->first();
        // dd($user);

        $user->delete();
    }

    public function memberApi(){
        $member = DB::table('users')->rightJoin('members','members.user_id','=','users.id');

        return $this->displayMember($member);
    }
}

app/Http/Controllers/Dashboard/Member/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Models\Member;

class ProfileController extends Controller
{
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = Member::where('user_id',$user->id)->first();

        // dd($user);

        return view('dashboard.member.user.profile.detail_profile',compact('user','member'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();

        return view('dashboard.member.user.profile.edit_profile',compact('user','member'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required'
        ]);
        
        $user = User::where('uuid',$id)->first();
        $member = $user->member()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;
        
        $user->update();

        //=========== member =============
        $member->province = $request->province;
        $member->address = $request->address;
        $member->hp = $request->hp;
        $member->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $member->birth_place = $request->birth_place;
        $member->gender = $request->gender;

        if ($request->hasFile('photo')) 
        {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/member',$photoName);
            $member->photo = $photoName;
        }
        $member->update();

        return redirect()->back()->with('success','Edit Success');
    }

    public function passwordEdit($uuid)
    {
        $user = User::where('uuid',$uuid)->first();

        return view('dashboard.member.user.profile.edit_password',compact('user'));
    }

    public function passwordUpdate(Request $request, $id)
    {
        $user = User::where('uuid',$id)->first();
        
        if ($request->password == $request->password2 && strlen($request->password) >= 8) {
            $user->password = bcrypt($request->password);
            $user->update();

            return redirect()->back()->with('success','Berhasil Merubah Password');
        }else{
            return redirect()->back()->with('info','Password tidak sama atau kurang dari 8 karakter');
        }
        
    }
}

resources/views/dashboard/member/add_member.blade.php
@extends('dashboard.master')
@section('content')
<div class="main-content">
  @include('dashboard.components.menu_dropdown')
  <form class="mb-5" action="{{route('member.store')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}} {{ method_field('POST')}}
    <div class="header bg-gradient-primary  pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block pb-5">Tambah Anggota</a>
        <div class="header-body">
          <div class="row">

            <div class="col-md-3">
              <div class="card bg-gradient-default shadow">
                <div class="card-body">
                    <img class="img-thumbnail d-block" src="{{asset('img/user.png')}}" id='img-upload' alt="">
                    <br>
                    <div class="input-group upload">
                      <label class="btn btn-primary shadow" for="photo">Upload Foto</label>
                      <input class="form-control d-none" value="{{ old('photo') }}" accept="image/jpeg,image/jpg,image/png,"
                        type="file" name="photo" id="photo">
                      <span class="errorval errorRegis" id="error_photo"></span>
                    </div>
                </div>
              </div>
            </div>

            <div class="col-md-9">
                <div class="card bg-gradient-default shadow">
                    <div class="card-body">
              <div class="form-group">
                <input required type="text" class="form-control" name="name" value="{{ old('name') }}" id="name"
                  placeholder="Masukan Nama">
                @error('name')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <input value="{{ old('email') }}" required type="email" class="form-control" name="email" id="email"
                  placeholder="Masukan Email">
                @error('email')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <input required type="password" class="form-control" id="password" name="password"
                  placeholder="Password">
                @error('password')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
            </div>
          </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid mt--7 mb-5">
      <div class="row">
        <div class="col-md-6">
          <div class="card bg-gradient-default shadow">
            <div class="card-body">
              <div class="form-group">
                <input type="number" class="form-control" name="hp" value="{{ old('hp') }}" id="hp"
                  placeholder="Handphone">
                @error('hp')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input style="cursor:pointer;" readonly type="text" class="form-control" name="birth_date"
                  value="{{ old('birth_date') }}" id="datepicker" placeholder="Tanggal Lahir">
                @error('birth_date')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="birth_place" value="{{ old('birth_place') }}"
                  id="birth_place" placeholder="Tempat Lahir">
                @error('birth_place')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="education" value="{{ old('education') }}" id="education"
                  placeholder="Pendidikan">
                @error('education')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <label class="text-white" for="income">Status Perkawinan</label>
                <select name="status" id="status" class="form-control">
                  <option {{old('status')=='Belum Kawin'?'selected':''}} value="Belum Kawin">Belum Kawin</option>
                  <option {{old('status')=='Sudah Kawin'?'selected':''}} value="Sudah Kawin">Sudah Kawin</option>
                </select>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="job" value="{{ old('job') }}" id="job"
                  placeholder="Pekerjaan">
                @error('job')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="skill" value="{{ old('skill') }}" id="skill"
                  placeholder="Keahlian">
                @error('skill')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="link" class="form-control" name="fb" value="{{ old('fb') }}" id="fb"
                  placeholder="Akun Facebook">
                @error('fb')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-6">
          <div class="card bg-gradient-default shadow">
            <div class="card-body">
              <div class="form-group">
                <label class="col-form-label text-white">Jenis Kelamin</label>
                <div class="custom-control custom-radio mb-3">
                    <input name="gender" class="custom-control-input" value="Pria" id="gender1" checked type="radio">
                    <label class="custom-control-label text-white" for="gender1">Pria</label>
                  </div>
                  <div class="custom-control custom-radio mb-3">
                    <input name="gender" class="custom-control-input" value="Wanita" id="gender2" type="radio">
                    <label class="custom-control-label text-white" for="gender2">Wanita</label>
                  </div>
              </div>

              <div class="form-group">
                <label for="" class="text-white">Posisi</label>
                <select class="form-control" name="position" id="position">
                  @if (Auth::user()->hasRole('master'))
                  <option {{ old('position')=='admin'?'selected':'' }} value="admin">Admin</option>
                  @endif
                  <option {{ old('position')=='member'?'selected':'' }} value="member">member</option>
                </select>
              </div>

              <div class="form-group">
                <label for="" class="text-white">Provinsi</label>
                <select class="form-control" name="province" id="province">
                  {{-- <option value="">----------</option> --}}
                  @foreach ($province as $province)
                  <option {{ old('province')==$province->id?'selected':'' }} value="{{ $province->id }}">
                    {{ $province->name }}</option>
                  @endforeach
                </select>
                @error('province')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <label id="city2" for="city" class="text-white">Kota</label>
                <select class="form-control" name="city" id="city">
                  {{-- <option value="">----------</option> --}}
                  @foreach ($city as $city)
                  <option class="{{ $city->province_id }}" value="{{ $city->id }}">{{$city->name}}</option>
                  @endforeach
                </select>
                @error('city')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <label class="text-white" for="">Alamat</label>
                <textarea type="text" class="form-control" name="address" id="address"
                  placeholder="">{{ old('address') }}</textarea>
                @error('address')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary mr-2 btn-block">Selesai</button>
  </form>
</div>
@endsection
@section('js')
<script src="{{asset('js/jquery-1.12.4.js')}}"></script>
<script src="{{asset('js/jquery-ui.js')}}"></script>
<script src="{{asset('js/jquery-chain.js')}}"></script>
@endsection

resources/views/dashboard/member/edit_member.blade.php
@extends('dashboard.master')
@section('content')
<div class="main-content">
  @include('dashboard.components.menu_dropdown')
  <form class="mb-5" action="{{route('member.update',$user->uuid)}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}} {{ method_field('PATCH')}}
    <div class="header bg-gradient-primary  pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
            @include('layouts.patrials.alerts')
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block pb-5">Edit Anggota</a>
        <div class="header-body">
          <div class="row">

            <div class="col-md-3">
              <div class="card bg-gradient-default shadow">
                <div class="card-body">
                    @if (isset($member->photo))
                    <img class="img-thumbnail d-block" src="{{asset('storage/member/'.$member->photo)}}" id='img-upload' alt="">
                    @else
                    <img class="img-thumbnail d-block" src="{{asset('img/user.png')}}" id='img-upload' alt="">
                    @endif
                    <br>
                    <div class="input-group upload">
                      <label class="btn btn-primary shadow" for="photo">Upload Foto</label>
                      <input class="form-control d-none" value="{{ old('photo') }}" accept="image/jpeg,image/jpg,image/png,"
                        type="file" name="photo" id="photo">
                      <span class="errorval errorRegis" id="error_photo"></span>
                    </div>
                </div>
              </div>
            </div>

            <div class="col-md-9">
                <div class="card bg-gradient-default shadow">
                    <div class="card-body">
              <div class="form-group">
                <input required type="text" class="form-control" name="name" value="{{ $user->name }}" id="name"
                  placeholder="Masukan Nama">
                @error('name')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <input value="{{ $user->email }}" required type="email" class="form-control" name="email" id="email"
                  placeholder="Masukan Email">
                @error('email')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <input data-toggle="tooltip" data-placement="bottom" title="Password asli di sensor otomatis" value="{{$user->password}}" required type="password" class="form-control" id="password" name="password"
                  placeholder="Password">
                @error('password')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
            </div>
          </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid mt--7 mb-5">
      <div class="row">
        <div class="col-md-6">
          <div class="card bg-gradient-default shadow">
            <div class="card-body">
              <div class="form-group">
                <input type="number" class="form-control" name="hp" value="{{ $member->hp }}" id="hp"
                  placeholder="Handphone">
                @error('hp')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input style="cursor:pointer;" type="text" readonly class="form-control" name="birth_date"
                  value="{{ date('d - m - Y',strtotime($member->birth_date)) }}" id="datepicker" placeholder="Tanggal Lahir">
                @error('birth_date')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="birth_place" value="{{ $member->birth_place }}"
                  id="birth_place" placeholder="Tempat Lahir">
                @error('birth_place')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="education" value="{{ $member->education }}" id="education"
                  placeholder="Pendidikan">
                @error('education')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <label class="text-white" for="income">Status Perkawinan</label>
                <select name="status" id="status" class="form-control">
                  <option {{$member->status=='Belum Kawin'?'selected':''}} value="Belum Kawin">Belum Kawin</option>
                  <option {{$member->status=='Sudah Kawin'?'selected':''}} value="Sudah Kawin">Sudah Kawin</option>
                </select>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="job" value="{{ $member->job }}" id="job"
                  placeholder="Pekerjaan">
                @error('job')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="skill" value="{{ $member->skill }}" id="skill"
                  placeholder="Keahlian">
                @error('skill')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
              <div class="form-group">
                <input type="link" class="form-control" name="fb" value="{{ $member->fb }}" id="fb"
                  placeholder="Akun Facebook">
                @error('fb')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-6">
          <div class="card bg-gradient-default shadow">
            <div class="card-body">
              <div class="form-group">
                <label class="col-form-label text-white">Jenis Kelamin</label>
                <div class="custom-control custom-radio mb-3">
                    <input {{$member->gender=='Pria'?'checked':''}} name="gender" class="custom-control-input" value="Pria" id="gender1" type="radio">
                    <label class="custom-control-label text-white" for="gender1">Pria</label>
                  </div>
                  <div class="custom-control custom-radio mb-3">
                    <input {{$member->gender=='Wanita'?'checked':''}} name="gender" class="custom-control-input" value="Wanita" id="gender2" type="radio">
                    <label class="custom-control-label text-white" for="gender2">Wanita</label>
                  </div>
              </div>

              <div class="form-group">
                <label for="" class="text-white">Provinsi</label>
                <select class="form-control" name="province" id="province">
                    {{-- <option value="">----------</option> --}}
                    @foreach ($province as $province)
                        <option {{ $province2->id==$province->id?'selected':'' }} value="{{ $province->id }}">{{ $province->name }}</option>
                    @endforeach
                </select>
                @error('province')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <label id="city2" for="city" class="text-white">Kota</label>
                <select class="form-control" name="city" id="city">
                    {{-- <option value="">----------</option> --}}
                    @foreach ($city as $city)
                        <option class="{{ $city->province_id }}" {{ $city2->id==$city->id?'selected':'' }} value="{{ $city->id }}">{{ $city->name }}</option>
                    @endforeach
                </select>
                @error('city')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>

              <div class="form-group">
                <label class="text-white" for="">Alamat</label>
                <textarea type="text" class="form-control" name="address" id="address"
                  placeholder="">{{$member->address }}</textarea>
                @error('address')
                <span class="mt-1 alert-danger" role="alert">
                  <small>{{ $message }}</small>
                </span>
                @enderror
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary mr-2 btn-block">Selesai</button>
  </form>
</div>
@endsection
@section('js')
<script src="{{asset('js/jquery-1.12.4.js')}}"></script>
<script src="{{asset('js/jquery-ui.js')}}"></script>
<script src="{{asset('js/jquery-chain.js')}}"></script>
@endsection